'''
Rosalind: Bioinformatics Stronghold
ID: DNA
Title: Counting DNA Nucleotides
Problem: 
Given: A DNA string s of length at most 1000 nt.

Return: Four integers (separated by spaces) counting the respective number of times that the symbols 'A', 'C', 'G', and 'T' occur in s.
'''

DNA = "TGTCAACTTGGTTCAAACATCACGGGAGAACTGGTCCCGTCTGATTACCCGGGTTTACATAGGCACAGGAGTACGTATATCGCGTAGTAAACTCGCCATGTCAGTAATGCTGAGTTAGCAACAGTTTCGGCAGGTGCCACGGAAGGTAGGGGCGAACAGACAAGTTACTGGTTCGGAGGTGCTTTTTCTCGCATCATATACTATCTTTGCTCACGGCGCTCGATGAACGGGTCCTTGATGCACGAGAGATGCGAGGAGCCGGCCGGAGCCGGTGTGGTGTCAATGTTGCGTTAGGACCCCGCTTCGTTAAAAACCCTGCTTGCCAAGCGCCCTACGCGGACCAAGTCTGGAGACCACCGCAAGTCGATATTTCTGTTCCCCCTGCCTAGGCCTCTACCATGACTTTCCACATTGCTTTCTTGGGTCACCGATCTTGAGACTCGCCCGTGATACACGCGAATGCAGCAGACGAACACGGCTATCGCACTAACTCATATACCTTAGATTCGGCTTTTACAGAAAGCCTAACGTGGAACAGTTACGCCCTTACCATCTCTGGCATCACGAACAGTCTTCGTAAGCGCCCTCGCGCAAGTACAATCATGCTTGAAAGACTAAACAACTCTGAATAGAGCTATCTGAAACGGACCGGAAGATTGAGACACAGAAATTTCACAACTCCCGATATTGCGCTAGTAAGATAAGCAATGAGCGTCACCAGTTACTCGCTCGTCTGGAAGTCTATTTCTCGTATACGTACATCGTGTGTAACAGGGCTTAAACCAGATCTCAGATAAGCTATTCGCCTCCTTTGGCGATGTACACATTTCACCGTGTGCCTGATTTGAAGTATTAGATTCGTATGGGCAAGGAAGGTTACGGTTAAGAATAAGGAACACGTTGCTCGAGCGGGCACCCCAATTACCCGCATGAGCTACCGTTGTAACCACGATAAGATTCCTCCGCAAGGATAACCCAAAAA"

A = DNA.count('A')
C = DNA.count('C')
G = DNA.count('G')
T = DNA.count('T')
output = "% 2d % 2d % 2d % 2d" %(A,C,G,T)

outF = open("DNAouput.txt","w")
outF.write(output)
outF.close()


