'''
Rosalind: Bioinformatics Stronghold
ID: RNA
Title: Transcribing DNA into RNA

Given: A DNA string s of length at most 1000 bp.

Return: The reverse complement sc of s.
'''
DNA = 'TAGCCATCGCTCTGGGAAGCCAGGTGGAAAAGAGTTCACGCTAGTGAGCCGTAGCCTAGTGCATCGTTTTTTTATGTTTCTGGCTCGTATATCACGATCACTCCTGTACAAACTGGGTTCGCGTCAATTGCGTTGAACGCCTGCATTGTGCGCATTGGTGTAAGGGGTGATATTAATGAGCGTCTCCTGGAGTGTTGACCCTTGAAAATATTCATTTAAATGTCCTCGGATTCTGTATAGACTGGGCCTTGGAATCTGAGGTACTGTCGTCGTTCAACATTACGTGCGAGAACCATATTCAACACCGTTCTGCGTTTTGCGATAGGGTATAAATGTAGGGCTTTCAAGGCTGCAGGAATGGCTGCTCGTTCGCTGCTTGACTGAGAAATTCTCCTCGGTATAAACGAAGGAAATTCGTGTTGCTTGGACCCGTTCGCCTCTGGGCACCGGGGTTCATTCAAAGAGTGATAAACGCTCGGGGCTACCATTCAGTGGATATCGGCTGCTGATGGTAGCGATCCGAAGGTTTGGGTAGCTCGCTAGTCCTGACCGCTTTTAGCTTTAACTATCGTTCATCACTTGTGAGTGCACGCGGCTGTGGGCTGAGACTCTATGCTTGGAATACGGCGACCGCGTTGCCAAGTCCGACGACCCCTGCTCTAAGGGCAAAGGAATAACGTAGAAAACTGTACCCGACATACCACGCAGAGTAGGAAGCGCCTCGGACCAGCCTGTCGGAGCCATTTGTGATGACTTGGTGTTTTTTCTAGCCAGGGCCGCTCCTGTCGGGTCTCGGTGCCGCGTAACAGCTTGTACAGCGGACCATGGTCGTCCCTCCTTTCTGGGGGTCAATAGCGCAGGGTAGCGGGTCCGCTGTCCCCTCCCAGTATTCAGAATTGAACATACGCTGGCTCTCCGGCATACAGGGATAGAATCTGACGCCAGTGC'
reverse=DNA[::-1]
comp = ''
for i in reverse:
    if i == 'A':
        comp+='T'
    elif i == 'T':
        comp += 'A'
    elif i == 'C':
        comp += 'G'
    elif i == 'G':
        comp += 'C'

outF=open("DNAcomp.txt","w")
outF.write(comp)
outF.close()