'''
Rosalind: Bioinformatics Stronghold
ID: SUBS
Title: Finding a Motif in DNA

Given: Two DNA strings s and t (each of length at most 1 kbp).

Return: All locations of t as a substring of s.
'''

file=open('rosalind_subs.txt','r')

dna = file.readline().rstrip('\n')
motif = file.readline().rstrip('\n')

#dna = 'ACTTTTGAGCGATGAGCGACTGAGCGAAATCTGAGCGATGAGCGATTATGAGCGATGAGCGAAGTGGTGTGAGCGAATGAGCGATGAGCGATTGTGAGCGATTGTGAGCGATGAGCGACTGAGCGAATGAGCGATGAGCGACCTGAGCGATAGTGATGAGCGATGAGCGACCCGTTTTTGAGCGATGAGCGAGTTGAGCGATGAGCGATGAGCGAAGACCTGAGCGATGAGCGATCTCTCCAAACTGAGCGATATGAGCGATGAGCGAAACTGAGCGATGAGCGATATATGAGCGATGAGCGATGAGCGAATGTGAGCGATGAGCGATGAGCGAATGAGCGAAATGAGCGAGATGAGCGAATTGAGCGATGAGCGATCTGAGCGATGGTCCTTGAGCGAGGTAATTTGAGCGAGTCTATTGTTCGTGGTGAGCGACTCTGAGCGATGAGCGATCCGACGTCGAGTTGAGCGACTGAGCGACTACTGAGCGACCTGAGCGAATGTTATTGAGCGATGAGCGAGATGAGCGACTGAGCGATCGTCCTGCTTGAGCGACTGAGCGATGAGCGATGAGCGATCAACGGTGAGCGAATGAGCGATGACCTCTTGGACAGTGAGCGAGCTACATTACAAAGGGTGAGCGAGCAATATTGAGCGATGAGCGATGAGCGATGAGCGATTGAGCGAATGAGCGACCTCACGTGGATGAGCGACTCTGAGCGATGGACCCGGCCTGAGCGATGAGCGAACTGAGCGAGTGTTGAGCGATTTGAGCGACTCGGGCTTGCGTGAGCGACTACTTGAGCGAGTGAGCGAAATGACGAGTGAGCGAACTTGAGCGATGAGCGAATGTGAGCGATCACCTGAGCGAGTGAGCGA'
#motif = 'TGAGCGATG'
motif_num = []

for i in range(0, len(dna)):
	substr = dna[i:i+len(motif)]
	if substr == motif:
		motif_num.append(i+1)

new=open('motif_found.txt','w')
motif_count = ''
for i in motif_num:
	motif_count += str(i)
	motif_count += ' '
print(motif_count)
new.write(motif_count)
new.close()
file.close()

